# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-24 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Admin', 'Admin')], max_length=200),
        ),
    ]
